# Generated by Django 5.2 on 2025-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='last_loaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='loaded_in_memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_architecture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
