# Generated by Django 5.2 on 2025-04-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='is_active',
        ),
    ]
