# Generated by Django 5.2 on 2025-04-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mlmodel_last_loaded_mlmodel_loaded_in_memory_and_more'),
    ]

    operations = [
    ]
