# Generated by Django 5.2 on 2025-05-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250506_1241'),
    ]

    operations = [
    ]
