# Generated by Django 5.2 on 2025-04-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250427_1908'),
    ]

    operations = [
    ]
