# Generated by Django 5.2 on 2025-05-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250506_1329'),
    ]

    operations = [
    ]
