# Generated by Django 5.2 on 2025-04-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250427_1909'),
    ]

    operations = [
    ]
