# Generated by Django 5.2 on 2025-05-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250428_2119'),
    ]

    operations = [
    ]
