# Generated by Django 5.2 on 2025-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250501_1553'),
    ]

    operations = [
    ]
