# Generated by Django 5.2 on 2025-05-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250502_1451'),
    ]

    operations = [
    ]
